/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { VideoSegmentWhereInput } from "./VideoSegmentWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { VideoSegmentOrderByInput } from "./VideoSegmentOrderByInput";

@ArgsType()
class VideoSegmentFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => VideoSegmentWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => VideoSegmentWhereInput, { nullable: true })
  @Type(() => VideoSegmentWhereInput)
  where?: VideoSegmentWhereInput;

  @ApiProperty({
    required: false,
    type: [VideoSegmentOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [VideoSegmentOrderByInput], { nullable: true })
  @Type(() => VideoSegmentOrderByInput)
  orderBy?: Array<VideoSegmentOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { VideoSegmentFindManyArgs as VideoSegmentFindManyArgs };
